### PR TITLE
Fixes for author_name

### PR DESCRIPTION
**Pull request by Myned**
- Adds `author_name` field for certain index results
- Instead of only returning first creator, parse into comma-delimited string
- Fixes `MangaSource` creator list validation and closes [#16](https://github.com/FujiMakoto/pysaucenao/issues/16)

### CODE REVIEW

**Comment by FujiMakoto** [comment]
Thank you for the PR

As I commented on the issue, I think I'd rather have author_name always return a string of the first/primary author

Concatenating all authors into one comma seperated string could get extremely lengthy and cause issues for some systems where they need this value to be size constrained. In order for them to just pull the first author in this scenario, they'd then have to split the string by comma (and if the authors name for whatever reason already had a comma in it, then there's a bigger issue).

With that in mind, I want to keep an attribute that just provides a single author name via the `author_name` attribute, but we can introduce an `authors` attribute that is a `typing.List[]` and always returns a list of all authors that it can find, or an empty list if there are none.

I believe this would accommodate the best of both worlds.

**Comment by Myned** [comment]
Of course. I'd be fine with a new attribute. I'll revert those commits and see how to implement that, unless you wanted to take a look.

**Comment by FujiMakoto** [comment]
I'll take a look at this later today once I'm back at my work machine. You can submit an updated PR if you'd like! Otherwise I'll just adapt this one with the changes I mentioned above.

**Comment by Myned** [comment]
Seems to be working alright in my testing.
```python
print(type(results[0].authors))
print(results[0].authors)
print(results[0].author_name)

<class 'list'>
['nabi (uz02)']
nabi (uz02)
```
I did not implement an empty list if there is no author in favor of how the `urls` attribute was set up, which returns a None type. Let me know if that's not to your liking.

**Comment by FujiMakoto** [comment]
Looks good to me, thank you!

**Pull request merged**
